### PR TITLE
Ghc 8.6

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
@nomeata Could you make a new release, so we (who aren't at ICFP) can make things work with GHC-8.6? :)

**Comment by nomeata** [comment]
A revision bump ought to suffice, right?

**Comment by nomeata** [comment]
Cabal data revised.

**Comment by phadej** [comment]
The tests may fail (that's why I made a change to `examples/Dictionary.hs`) (i.e. you might get a report from Stackage that tests fail when it's upgraded to use GHC-8.6)

But for the library itself revision is fine, yes.

**Comment by phadej** [comment]
... and thanks for prompt response!

**Pull request merged**
