### PR TITLE
Support GHC 9.6

### PR DESCRIPTION
**Pull request by Bodigrim**
This builds atop of #71.

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks! I guess I should add 9.4 and 9.6 to CI first. I can probably do that tomorrow.

**Comment by nomeata** [comment]
If its ok with you I’ll wait for  https://github.com/haskell-CI/haskell-ci/issues/631 to have this CI-tested.

**Comment by Bodigrim** [comment]
> If its ok with you I’ll wait for [haskell-CI/haskell-ci#631](https://github.com/haskell-CI/haskell-ci/issues/631) to have this CI-tested.

Sure. The ticket has been just completed.

**Comment by nomeata** [comment]
Thanks! CI is green. Uploaded to hackage.

**Pull request merged**
