### PR TITLE
Use the latest haskell-ci to rebuild the travis config.

### PR DESCRIPTION
**Pull request by robrix**
🤞

### CODE REVIEW

**Comment by robrix** [comment]
@nomeata: it passes now! 🎉

**Comment by nomeata** [comment]
Perfect, thanks!

**Comment by robrix** [comment]
@nomeata: meant to ask if you’d like me to prep a new version for hackage as well—I’m happy to submit a PR to that effect if so (tho I obvs don’t have upload privs).

**Comment by nomeata** [comment]
Happens I already uploaded a new version :-)

**Comment by robrix** [comment]
😁 nice! thank you so much!

**Pull request merged**
