### PR TITLE
GHC 9.10.1 support

### PR DESCRIPTION
**Pull request by andrevdm**

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks! No source changes needed? Then I’ll just update the metadata via a hackage revision.

**Comment by andrevdm** [comment]
It compiles and test pass locally :) I PRed though to see if CI passes (and it does)
Would be great as a metadata update though, so I'll close this

Thanks!

**Comment by nomeata** [comment]
I’d still like to have it in the repo for the next release, sorry for the confusion!

**Comment by Bodigrim** [comment]
@nomeata @andrevdm are you sure about this? `inspection-testing` worked fine with GHC 9.10, which corresponds to `base-4.20`. This PR allows building against `base-4.21`, presumably to be a part of future GHC 9.12. Isn't it too early? If anything, it does not make terribly much sense to relax `base` but keep `build-depends: ghc < 9.11`.

**Comment by andrevdm** [comment]
Wow, no, I seem to have got something wrong there then. I was pretty sure it was not compiling for 9.10 for me but those bounds make no sense... Let me check again and submit a fix, sorry for the confusion.

**Comment by andrevdm** [comment]
#79 submitted. Sorry for that and thanks @Bodigrim for taking the time to check that

**Pull request merged**
