### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by phadej**
I think that they won't run until pushed by someone with write access to the repository. Lets see.

### CODE REVIEW

**Comment by phadej** [comment]
https://github.com/phadej/inspection-testing/runs/1665046137?check_suite_focus=true it almost passes. GHC-8.2.1 is not available for `bionic` in Herbert's PPA.  

I'd drop non-latest minor releases for older GHCs, I could amend the PR, if it's ok.

**Comment by nomeata** [comment]
> I'd drop non-latest minor releases for older GHCs, I could amend the PR, if it's ok.

That’s ok!

**Comment by nomeata** [comment]
Do you plan to take more long-term responsibility for `inspection-testing`? It could certainly use some co-maintainer who uses it more than I do… :-)

**Comment by nomeata** [comment]
Merged, let’s see what happens. We can refine on master.

**Comment by phadej** [comment]
I'd politely decline, I've got a lot on my plate.

**Comment by nomeata** [comment]
Smart move :-D

**Pull request merged**
