### PR TITLE
Add example of testing for Worker/Wrapper transformation

### PR DESCRIPTION
**Pull request by rjmk**
This was the way that I thought to do it. Happy to hear if there's a better way, but otherwise thought it might be a useful example

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks! Looks reasonable at first. Does this test actually pass, though? (The name “bad” fold doesn’t sound like it would).

**Comment by rjmk** [comment]
Ah, sorry, bad naming! In my head, this example was for passing around monoid-ish dictionaries that are law-violating (thus 'bad'). Will rename.

It does indeed pass (and fails when optimisations are off)

**Comment by nomeata** [comment]
Ok, no imagine to be a first-time user of `inspection-testing`, and you are browsing the example. Probably you don't imediatelly see which transformation is happening here that you want to check for. Care to add a few lines of comments, explaining the transformation that is happening, and why this test would detect it?

With that I’ll happily merge this :-)

**Comment by rjmk** [comment]
Docs added

**Comment by nomeata** [comment]
Thanks!

**Comment by nomeata** [comment]
I am not sure why CI didn't run on the PR, but it seems stuff broke: https://travis-ci.org/github/nomeata/inspection-testing/jobs/667586556
Can you take a look?

**Pull request merged**
