### PR TITLE
Support GHC 9.2

### PR DESCRIPTION
**Pull request by Bodigrim**
I suspect it's too early to release this before GHC 9.2 RC is out, but getting this patch into `master` would be nice. Tested with `ghc-9.2.0.20210422`.

### CODE REVIEW

**Review by nomeata — APPROVED** [review]
Thanks a bunch

**Comment by Bodigrim** [comment]
Since GHC 9.2 rc1 is available, I'd appreciate a release.

**Comment by nomeata** [comment]
Trying, with CI, in https://github.com/nomeata/inspection-testing/pull/64, but the PPA doesn’t have GHC yet?

**Comment by nomeata** [comment]
Done

**Pull request merged**
